### PR TITLE
Added unit tests

### PR DESCRIPTION
**Pull request by dvcorreia1984**
In this pull request the following was done: 

1. Unit tests were added to the calculate.js and operate.js functions.

### CODE REVIEW

**Review by AbelG101 — COMMENTED** [review]
# Hi @dvcorreia1984 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Please keep in mind that this is a pair programming activity, which means that each team member needs to make a substantial contribution to the project. To ensure that everyone is equally involved, please reach out to your team member/s and encourage them to add some commits. This will help ensure that the project is completed successfully and that everyone has the opportunity to contribute their skills and expertise. Thank you!

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by dvcorreia1984** [comment]
Hi @AbelG101 

My partner has not made any contact with me this week. I am currently reaching out to student success to ask them for guidance.

**Comment by AbelG101** [comment]
Hello @dvcorreia1984 In the future please attach the screenshot in your PR description so we don't cause any inconvenience by Invalidating your PR.

**Review by LionRouge1 — APPROVED** [review]
Hi @dvcorreia1984, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

done

## Highlights
- Great job, your project is error free :+1: 
- Nice work you meet all the requirements :1st_place_medal: 
- All linters passed :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
